# Generated by Django 5.2 on 2025-06-08 20:39

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uuidtaggeditem_alter_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
